fn main() {
    // 声明应用自定义命令(#[tauri::command]):构建期据此在 permissions/autogenerated/
    // 生成 allow-<cmd>/deny-<cmd> 权限,capabilities/default.json 引用它们完成授权。
    // 缺了这一步,远程源(桌面版页面由本机后端 http://127.0.0.1 托管,算远程源)
    // 调自定义命令一律被 ACL 拒绝(Command xxx not allowed by ACL)。
    // 新增 #[tauri::command] 时必须同步加进这个列表和 capabilities/default.json。
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(
            tauri_build::AppManifest::new().commands(&[
                "desktop_ping",
                "check_update",
                "download_and_install_update",
                "restart_app",
                "set_update_proxy",
                "get_update_proxy",
                "enable_close_guard",
                "close_app",
                "hide_to_tray",
            ]),
        ),
    )
    .expect("tauri-build 失败")
}
