"""baseline initial schema

Revision ID: fe553853d66d
Revises: 
Create Date: 2026-08-26 17:50:51.839947

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe553853d66d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('invite_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_codes_code'), ['code'], unique=True)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=200), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('llm_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_usage_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_user_id'), ['user_id'], unique=False)

    op.create_table('tendency_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tendency_presets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tendency_presets_scope'), ['scope'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('birthday_wishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('occasion', sa.String(length=20), server_default='birthday', nullable=False),
    sa.Column('honoree_name', sa.String(length=60), nullable=False),
    sa.Column('relationship', sa.String(length=20), nullable=False),
    sa.Column('milestone', sa.String(length=80), nullable=False),
    sa.Column('memories', sa.JSON(), nullable=False),
    sa.Column('sender_desc', sa.String(length=80), nullable=False),
    sa.Column('tone', sa.String(length=40), nullable=False),
    sa.Column('custom_tone', sa.String(length=120), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('pack', sa.String(length=40), server_default='', nullable=False),
    sa.Column('direction', sa.String(length=40), nullable=False),
    sa.Column('style_hints', sa.String(length=160), server_default='', nullable=False),
    sa.Column('style_name', sa.String(length=60), nullable=False),
    sa.Column('style_cn', sa.Text(), nullable=False),
    sa.Column('style_en', sa.Text(), nullable=False),
    sa.Column('negative', sa.Text(), nullable=False),
    sa.Column('candidates', sa.JSON(), nullable=False),
    sa.Column('chosen', sa.Integer(), nullable=False),
    sa.Column('clip', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('birthday_wishes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_birthday_wishes_user_id'), ['user_id'], unique=False)

    op.create_table('series_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('look', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(length=40), nullable=False),
    sa.Column('default_duration_s', sa.Integer(), nullable=False),
    sa.Column('style_hints', sa.String(length=160), server_default='', nullable=False),
    sa.Column('ref_images', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('series_characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_characters_user_id'), ['user_id'], unique=False)

    op.create_table('series_episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('plot', sa.Text(), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['character_id'], ['series_characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('series_episodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_episodes_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_episodes_character_id'), ['character_id'], unique=False)

    op.create_table('feature_usage',
    sa.Column('feature', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feature', 'user_id')
    )

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=False),
    sa.Column('target_chapters', sa.Integer(), nullable=False),
    sa.Column('target_words_per_chapter', sa.Integer(), nullable=False),
    sa.Column('word_guard_enabled', sa.Boolean(), nullable=False),
    sa.Column('word_guard_ratio', sa.Float(), nullable=False),
    sa.Column('auto_split_enabled', sa.Boolean(), nullable=False),
    sa.Column('review_pass_threshold', sa.Integer(), nullable=False),
    sa.Column('review_auto_revise', sa.Boolean(), nullable=False),
    sa.Column('review_max_revisions', sa.Integer(), nullable=False),
    sa.Column('queue_require_approved', sa.Boolean(), nullable=False),
    sa.Column('global_tendency', sa.JSON(), nullable=False),
    sa.Column('concept', sa.JSON(), nullable=True),
    sa.Column('dna', sa.JSON(), nullable=True),
    sa.Column('canon', sa.JSON(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('setup_state', sa.String(length=20), nullable=True),
    sa.Column('chat_log', sa.JSON(), nullable=True),
    sa.Column('macro_plan', sa.JSON(), nullable=True),
    sa.Column('style_memo', sa.Text(), nullable=True),
    sa.Column('world_rules', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('outline_stale', sa.Boolean(), nullable=False),
    sa.Column('render_mode', sa.String(length=10), server_default='lite', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)

    op.create_table('promo_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('angles', sa.JSON(), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=40), nullable=False),
    sa.Column('style_name', sa.String(length=60), nullable=False),
    sa.Column('style_cn', sa.Text(), nullable=False),
    sa.Column('style_en', sa.Text(), nullable=False),
    sa.Column('negative', sa.Text(), nullable=False),
    sa.Column('landmarks', sa.JSON(), nullable=False),
    sa.Column('material_notes', sa.Text(), nullable=False),
    sa.Column('chat_log', sa.JSON(), nullable=False),
    sa.Column('brief', sa.JSON(), nullable=False),
    sa.Column('brief_locked', sa.Boolean(), nullable=False),
    sa.Column('script', sa.JSON(), nullable=False),
    sa.Column('pack', sa.JSON(), nullable=False),
    sa.Column('chunks', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promo_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promo_plans_user_id'), ['user_id'], unique=False)

    op.create_table('provider_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('interface_format', sa.String(length=20), nullable=False),
    sa.Column('api_key', sa.String(length=300), nullable=False),
    sa.Column('base_url', sa.String(length=300), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('thinking_mode', sa.String(length=10), server_default='', nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_default_fast', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_configs_interface_format'), ['interface_format'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_configs_user_id'), ['user_id'], unique=False)

    op.create_table('provider_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('api_key', sa.String(length=300), nullable=False),
    sa.Column('base_url', sa.String(length=300), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_provider_per_user')
    )
    with op.batch_alter_table('provider_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_settings_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_settings_user_id'), ['user_id'], unique=False)

    op.create_table('architecture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('core_seed', sa.Text(), nullable=False),
    sa.Column('character_dynamics', sa.Text(), nullable=False),
    sa.Column('world_building', sa.Text(), nullable=False),
    sa.Column('plot_architecture', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('concept_stale', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('architecture', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_architecture_project_id'), ['project_id'], unique=False)

    op.create_table('birthday_shoots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wish_id', sa.Integer(), nullable=False),
    sa.Column('shoot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wish_id'], ['birthday_wishes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('birthday_shoots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_birthday_shoots_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_birthday_shoots_wish_id'), ['wish_id'], unique=True)

    op.create_table('chapter_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('rolling_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_summaries_chapter_number'), ['chapter_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_summaries_project_id'), ['project_id'], unique=False)

    op.create_table('drama_episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('ep_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('source_chapter', sa.Integer(), nullable=False),
    sa.Column('source_chapters', sa.JSON(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('recap', sa.Text(), nullable=False),
    sa.Column('cliffhanger', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('duration_target_s', sa.Integer(), nullable=False),
    sa.Column('script', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'ep_index', name='uq_drama_ep_index')
    )
    with op.batch_alter_table('drama_episodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drama_episodes_project_id'), ['project_id'], unique=False)

    op.create_table('drama_scene_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('appearance_cn', sa.Text(), nullable=False),
    sa.Column('appearance_en', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_drama_scene_name')
    )
    with op.batch_alter_table('drama_scene_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drama_scene_cards_project_id'), ['project_id'], unique=False)

    op.create_table('drama_style_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('style_name', sa.String(length=60), nullable=False),
    sa.Column('direction', sa.String(length=40), nullable=False),
    sa.Column('style_cn', sa.Text(), nullable=False),
    sa.Column('style_en', sa.Text(), nullable=False),
    sa.Column('negative', sa.Text(), nullable=False),
    sa.Column('ratio', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drama_style_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drama_style_cards_project_id'), ['project_id'], unique=True)

    op.create_table('drama_trailers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('target_s', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('shots', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drama_trailers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drama_trailers_project_id'), ['project_id'], unique=True)

    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('base_profile', sa.JSON(), nullable=False),
    sa.Column('retired', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_project_id'), ['project_id'], unique=False)

    op.create_table('foreshadowings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('chapter_planted', sa.Integer(), nullable=False),
    sa.Column('expected_payoff_chapter', sa.Integer(), nullable=True),
    sa.Column('earliest_payoff_chapter', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('payoff_chapter', sa.Integer(), nullable=True),
    sa.Column('reinforcement_chapters', sa.JSON(), nullable=False),
    sa.Column('importance', sa.String(length=10), nullable=False),
    sa.Column('required_hints', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('foreshadowings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_foreshadowings_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_foreshadowings_status'), ['status'], unique=False)

    op.create_table('mood_clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source_project_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=20), server_default='mood', nullable=False),
    sa.Column('theme', sa.String(length=40), nullable=False),
    sa.Column('custom_theme', sa.String(length=120), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=40), nullable=False),
    sa.Column('inspiration', sa.Text(), nullable=False),
    sa.Column('dialogue_style', sa.String(length=20), server_default='auto', nullable=False),
    sa.Column('pacing', sa.String(length=20), server_default='auto', nullable=False),
    sa.Column('intensity', sa.String(length=20), server_default='auto', nullable=False),
    sa.Column('style_hints', sa.String(length=160), server_default='', nullable=False),
    sa.Column('style_name', sa.String(length=60), nullable=False),
    sa.Column('style_cn', sa.Text(), nullable=False),
    sa.Column('style_en', sa.Text(), nullable=False),
    sa.Column('negative', sa.Text(), nullable=False),
    sa.Column('candidates', sa.JSON(), nullable=False),
    sa.Column('chosen', sa.Integer(), nullable=False),
    sa.Column('clip', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mood_clips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mood_clips_source_project_id'), ['source_project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mood_clips_user_id'), ['user_id'], unique=False)

    op.create_table('outlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('chapter_role', sa.String(length=100), nullable=False),
    sa.Column('chapter_purpose', sa.Text(), nullable=False),
    sa.Column('suspense_level', sa.String(length=50), nullable=False),
    sa.Column('foreshadowing', sa.Text(), nullable=False),
    sa.Column('plot_twist_level', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('beats', sa.JSON(), nullable=False),
    sa.Column('characters_involved', sa.JSON(), nullable=False),
    sa.Column('key_items', sa.JSON(), nullable=False),
    sa.Column('scene_location', sa.String(length=200), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outlines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outlines_chapter_number'), ['chapter_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_outlines_project_id'), ['project_id'], unique=False)

    op.create_table('promo_shots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('scene_name', sa.String(length=200), nullable=False),
    sa.Column('characters', sa.JSON(), nullable=False),
    sa.Column('action_desc', sa.Text(), nullable=False),
    sa.Column('shot_type', sa.String(length=20), nullable=False),
    sa.Column('camera', sa.String(length=20), nullable=False),
    sa.Column('dialogue', sa.Text(), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('prompt_cn', sa.Text(), nullable=False),
    sa.Column('prompt_en', sa.Text(), nullable=False),
    sa.Column('negative', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['promo_id'], ['promo_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promo_shots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promo_shots_promo_id'), ['promo_id'], unique=False)

    op.create_table('writing_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('writing_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_writing_cards_project_id'), ['project_id'], unique=False)

    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('outline_id', sa.Integer(), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('draft_content', sa.Text(), nullable=False),
    sa.Column('final_content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('outline_version_used', sa.Integer(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_snapshot', sa.Text(), nullable=False),
    sa.Column('proofread_snapshot', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['outline_id'], ['outlines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapters_chapter_number'), ['chapter_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapters_project_id'), ['project_id'], unique=False)

    op.create_table('clip_shoots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('shoot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['mood_clips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clip_shoots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clip_shoots_clip_id'), ['clip_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_clip_shoots_user_id'), ['user_id'], unique=False)

    op.create_table('drama_character_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('appearance_cn', sa.Text(), nullable=False),
    sa.Column('appearance_en', sa.Text(), nullable=False),
    sa.Column('outfit_cn', sa.Text(), nullable=False),
    sa.Column('voice_desc', sa.Text(), nullable=False),
    sa.Column('tts_hint', sa.Text(), nullable=False),
    sa.Column('reading_notes', sa.Text(), nullable=False),
    sa.Column('ref_prompt_cn', sa.Text(), nullable=False),
    sa.Column('ref_prompt_en', sa.Text(), nullable=False),
    sa.Column('ref_images', sa.JSON(), nullable=False),
    sa.Column('voice_ref', sa.String(length=300), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_drama_char_name')
    )
    with op.batch_alter_table('drama_character_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drama_character_cards_project_id'), ['project_id'], unique=False)

    op.create_table('drama_production_packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('pack', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['drama_episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drama_production_packs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drama_production_packs_episode_id'), ['episode_id'], unique=True)

    op.create_table('drama_shots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('scene_name', sa.String(length=200), nullable=False),
    sa.Column('characters', sa.JSON(), nullable=False),
    sa.Column('action_desc', sa.Text(), nullable=False),
    sa.Column('shot_type', sa.String(length=20), nullable=False),
    sa.Column('camera', sa.String(length=20), nullable=False),
    sa.Column('dialogue', sa.Text(), nullable=False),
    sa.Column('emotion', sa.String(length=20), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('prompt_cn', sa.Text(), nullable=False),
    sa.Column('prompt_en', sa.Text(), nullable=False),
    sa.Column('negative', sa.Text(), nullable=False),
    sa.Column('motion_cn', sa.Text(), nullable=False),
    sa.Column('motion_en', sa.Text(), nullable=False),
    sa.Column('assets', sa.JSON(), nullable=False),
    sa.Column('clip_ref', sa.String(length=500), nullable=False),
    sa.Column('done_still', sa.Boolean(), nullable=False),
    sa.Column('done_video', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['drama_episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drama_shots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drama_shots_episode_id'), ['episode_id'], unique=False)

    op.create_table('facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('fact_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.Integer(), nullable=True),
    sa.Column('importance', sa.String(length=10), nullable=False),
    sa.Column('source_chapter', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facts_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facts_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facts_valid_from'), ['valid_from'], unique=False)

    op.create_table('outline_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outline_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('change_type', sa.String(length=10), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['outline_id'], ['outlines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outline_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outline_versions_outline_id'), ['outline_id'], unique=False)

    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('from_entity_id', sa.Integer(), nullable=False),
    sa.Column('to_entity_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=100), nullable=False),
    sa.Column('valid_from', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationships_project_id'), ['project_id'], unique=False)

    op.create_table('chapter_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('issue_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content_hash', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_issues_chapter_id'), ['chapter_id'], unique=False)

    op.create_table('chapter_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('contract', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=16), nullable=False),
    sa.Column('extract_status', sa.String(length=20), nullable=False),
    sa.Column('extract_error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_states_chapter_id'), ['chapter_id'], unique=True)

    op.create_table('chapter_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('draft_content', sa.Text(), nullable=False),
    sa.Column('final_content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_versions_chapter_id'), ['chapter_id'], unique=False)

    op.create_table('knowledge_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('knower', sa.String(length=50), nullable=False),
    sa.Column('known_from_chapter', sa.Integer(), nullable=False),
    sa.Column('knower_state', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_states_fact_id'), ['fact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_states_knower'), ['knower'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_states_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###



    op.create_table('render_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(length=300), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('resolution', sa.String(length=10), nullable=False),
    sa.Column('workflow_i2v', sa.String(length=120), nullable=False),
    sa.Column('workflow_t2v', sa.String(length=120), nullable=False),
    sa.Column('workflow_tts', sa.String(length=120), nullable=False),
    sa.Column('workflow_talk', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_render_config_per_user')
    )
    with op.batch_alter_table('render_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_render_configs_user_id'), ['user_id'], unique=False)

    op.create_table('render_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('line', sa.String(length=10), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('shot_id', sa.Integer(), nullable=True),
    sa.Column('clip_id', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('workflow_id', sa.String(length=120), nullable=False),
    sa.Column('provider_task_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result_path', sa.String(length=300), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('render_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_render_tasks_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_render_tasks_line'), ['line'], unique=False)
        batch_op.create_index(batch_op.f('ix_render_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_render_tasks_episode_id'), ['episode_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_render_tasks_shot_id'), ['shot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_render_tasks_clip_id'), ['clip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_render_tasks_status'), ['status'], unique=False)


    op.create_table('tts_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=16), nullable=False),
    sa.Column('voice_src', sa.String(length=300), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('emotion', sa.String(length=20), nullable=False),
    sa.Column('workflow_id', sa.String(length=120), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    with op.batch_alter_table('tts_tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tts_tracks_user_id'), ['user_id'], unique=False)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tts_tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tts_tracks_user_id'))

    op.drop_table('tts_tracks')
    with op.batch_alter_table('knowledge_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_states_project_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_states_knower'))
        batch_op.drop_index(batch_op.f('ix_knowledge_states_fact_id'))

    op.drop_table('knowledge_states')
    with op.batch_alter_table('chapter_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_versions_chapter_id'))

    op.drop_table('chapter_versions')
    with op.batch_alter_table('chapter_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_states_chapter_id'))

    op.drop_table('chapter_states')
    with op.batch_alter_table('chapter_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_issues_chapter_id'))

    op.drop_table('chapter_issues')
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationships_project_id'))

    op.drop_table('relationships')
    with op.batch_alter_table('outline_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outline_versions_outline_id'))

    op.drop_table('outline_versions')
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facts_valid_from'))
        batch_op.drop_index(batch_op.f('ix_facts_project_id'))
        batch_op.drop_index(batch_op.f('ix_facts_entity_id'))

    op.drop_table('facts')
    with op.batch_alter_table('drama_shots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drama_shots_episode_id'))

    op.drop_table('drama_shots')
    with op.batch_alter_table('drama_production_packs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drama_production_packs_episode_id'))

    op.drop_table('drama_production_packs')
    with op.batch_alter_table('drama_character_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drama_character_cards_project_id'))

    op.drop_table('drama_character_cards')
    with op.batch_alter_table('clip_shoots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clip_shoots_user_id'))
        batch_op.drop_index(batch_op.f('ix_clip_shoots_clip_id'))

    op.drop_table('clip_shoots')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapters_project_id'))
        batch_op.drop_index(batch_op.f('ix_chapters_chapter_number'))

    op.drop_table('chapters')
    with op.batch_alter_table('writing_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_writing_cards_project_id'))

    op.drop_table('writing_cards')
    with op.batch_alter_table('promo_shots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promo_shots_promo_id'))

    op.drop_table('promo_shots')
    with op.batch_alter_table('outlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outlines_project_id'))
        batch_op.drop_index(batch_op.f('ix_outlines_chapter_number'))

    op.drop_table('outlines')
    with op.batch_alter_table('mood_clips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mood_clips_user_id'))
        batch_op.drop_index(batch_op.f('ix_mood_clips_source_project_id'))

    op.drop_table('mood_clips')
    with op.batch_alter_table('foreshadowings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_foreshadowings_status'))
        batch_op.drop_index(batch_op.f('ix_foreshadowings_project_id'))

    op.drop_table('foreshadowings')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_project_id'))
        batch_op.drop_index(batch_op.f('ix_entities_entity_type'))

    op.drop_table('entities')
    with op.batch_alter_table('drama_trailers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drama_trailers_project_id'))

    op.drop_table('drama_trailers')
    with op.batch_alter_table('drama_style_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drama_style_cards_project_id'))

    op.drop_table('drama_style_cards')
    with op.batch_alter_table('drama_scene_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drama_scene_cards_project_id'))

    op.drop_table('drama_scene_cards')
    with op.batch_alter_table('drama_episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drama_episodes_project_id'))

    op.drop_table('drama_episodes')
    with op.batch_alter_table('chapter_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_summaries_project_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_summaries_chapter_number'))

    op.drop_table('chapter_summaries')
    with op.batch_alter_table('birthday_shoots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_birthday_shoots_wish_id'))
        batch_op.drop_index(batch_op.f('ix_birthday_shoots_user_id'))

    op.drop_table('birthday_shoots')
    with op.batch_alter_table('architecture', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_architecture_project_id'))

    op.drop_table('architecture')
    with op.batch_alter_table('provider_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_settings_user_id'))
        batch_op.drop_index(batch_op.f('ix_provider_settings_provider'))

    op.drop_table('provider_settings')
    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_configs_user_id'))
        batch_op.drop_index(batch_op.f('ix_provider_configs_interface_format'))

    op.drop_table('provider_configs')
    with op.batch_alter_table('promo_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promo_plans_user_id'))

    op.drop_table('promo_plans')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))

    op.drop_table('projects')
    with op.batch_alter_table('birthday_wishes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_birthday_wishes_user_id'))

    op.drop_table('birthday_wishes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('tendency_presets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tendency_presets_scope'))

    op.drop_table('tendency_presets')
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_user_id'))
        batch_op.drop_index(batch_op.f('ix_llm_usage_model'))

    op.drop_table('llm_usage')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_owner_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_kind'))

    op.drop_table('jobs')
    with op.batch_alter_table('invite_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_codes_code'))

    op.drop_table('invite_codes')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
