"""projects 加 finished 列(完本标记)

作者手动标记全书已完成。完本后前端置灰重命名/删除,后端接口也在 finished 下
拦截(409),防误删误改。Boolean 列带 server_default='0':SQLite ADD COLUMN
NOT NULL 不带默认值会炸存量库(0004 同款坑)。

Revision ID: a52a7aed8264
Revises: b3e9f2c41d70
Create Date: 2026-09-01 10:31:15.664250

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a52a7aed8264'
down_revision: Union[str, None] = 'b3e9f2c41d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _finished_exists() -> bool:
    """查 projects 表当前是否已有 finished 列(幂等用)。

    存量库可能已被 app/migrate.py 的手写 ALTER 加过列;Alembic 再 ADD
    会因 duplicate column 报错,故升级前先探,已有则跳过。
    """
    insp = sa.inspect(op.get_bind())
    cols = {c["name"] for c in insp.get_columns("projects")}
    return "finished" in cols


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _finished_exists():
        with op.batch_alter_table('projects', schema=None) as batch_op:
            batch_op.add_column(sa.Column('finished', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if _finished_exists():
        with op.batch_alter_table('projects', schema=None) as batch_op:
            batch_op.drop_column('finished')
    # ### end Alembic commands ###
