# -*- coding: utf-8 -*-
# 基线迁移的步骤注册表:顺序即 0001 原文件的执行顺序(含 downgrade 的历史怪癖:
# series_*/feature_usage/render_* 五张表自动生成时就没有 drop 步骤,原样保留)。
from __future__ import annotations

from . import chapters, drama, media, platform, projects, render

UPGRADE_STEPS = [
    platform.create_app_settings,
    platform.create_invite_codes,
    platform.create_jobs,
    platform.create_llm_usage,
    platform.create_tendency_presets,
    platform.create_users,
    media.create_birthday_wishes,
    media.create_series_characters,
    media.create_series_episodes,
    platform.create_feature_usage,
    projects.create_projects,
    media.create_promo_plans,
    render.create_provider_configs,
    render.create_provider_settings,
    projects.create_architecture,
    media.create_birthday_shoots,
    chapters.create_chapter_summaries,
    drama.create_drama_episodes,
    drama.create_drama_scene_cards,
    drama.create_drama_style_cards,
    drama.create_drama_trailers,
    projects.create_entities,
    projects.create_foreshadowings,
    media.create_mood_clips,
    projects.create_outlines,
    media.create_promo_shots,
    projects.create_writing_cards,
    chapters.create_chapters,
    media.create_clip_shoots,
    drama.create_drama_character_cards,
    drama.create_drama_production_packs,
    drama.create_drama_shots,
    projects.create_facts,
    projects.create_outline_versions,
    projects.create_relationships,
    chapters.create_chapter_issues,
    chapters.create_chapter_states,
    chapters.create_chapter_versions,
    projects.create_knowledge_states,
    render.create_render_configs,
    render.create_render_tasks,
    render.create_tts_tracks,
]

DOWNGRADE_STEPS = [
    render.drop_tts_tracks,
    projects.drop_knowledge_states,
    chapters.drop_chapter_versions,
    chapters.drop_chapter_states,
    chapters.drop_chapter_issues,
    projects.drop_relationships,
    projects.drop_outline_versions,
    projects.drop_facts,
    drama.drop_drama_shots,
    drama.drop_drama_production_packs,
    drama.drop_drama_character_cards,
    media.drop_clip_shoots,
    chapters.drop_chapters,
    projects.drop_writing_cards,
    media.drop_promo_shots,
    projects.drop_outlines,
    media.drop_mood_clips,
    projects.drop_foreshadowings,
    projects.drop_entities,
    drama.drop_drama_trailers,
    drama.drop_drama_style_cards,
    drama.drop_drama_scene_cards,
    drama.drop_drama_episodes,
    chapters.drop_chapter_summaries,
    media.drop_birthday_shoots,
    projects.drop_architecture,
    render.drop_provider_settings,
    render.drop_provider_configs,
    media.drop_promo_plans,
    projects.drop_projects,
    media.drop_birthday_wishes,
    platform.drop_users,
    platform.drop_tendency_presets,
    platform.drop_llm_usage,
    platform.drop_jobs,
    platform.drop_invite_codes,
    platform.drop_app_settings,
]
